name: pre deploy bot
run-name: Check lint 🚀
on: 
  pull_request:

jobs:
  pre-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js and Bun
        uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Check lint
        run: bun lint:check
